apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: ""
    workflow: ""
  name: ""
  namespace: ""
spec:
  template:
    metadata:
      labels:
        workflow: ""
        app: ""
    spec:
      containers:
      - args: []
        command: []
        image: ""
        # imagePullPolicy: Always
        imagePullPolicy: "IfNotPresent"
        name: "workflow-executor"
        resources: {}
        env:
        # - name: NODE_ID
        #   value: ""
        # - name: ADDRESS
        #   value: ""
        - name: PORT
          value: "5001"
        # - name: NETWORK
        #   value: ""
        - name: DATABASE_URL
          value: "sqlite:///databasenode.db"
        ports:
        - containerPort: 5001
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: db-operator
      serviceAccountName: db-operator
status: {}
